### ISSUE TITLE
Comment is too spammy

### ISSUE THREAD

**Issue by mandolaerik** [z0al/dependent-issues#318]
Hi,

The default message is too spammy in my taste, I much prefer a minimal clean comment as seen in https://github.com/Levi-Lesches/blocking-issues

I have created a fork that adapts Dependent Issues to something similar: https://github.com/mandolaerik/dependent-issues

Would it make sense to at least make this configurable?

**Comment by z0al** [comment]
> Would it make sense to at least make this configurable?

💯. Would you be able to work on that?

We could support `{{ dependencies }}` token so you can place the list wherever you want. For example

```yaml
# ...
with:
  comment:
    This PR is blocked by:

    {{ dependencies }}

    Have a nice day!
```

In the code we could do a simple match and replace:

```javascript
customMessage.replace(/\{\{\s*dependencies\s*\}\}/i, dependenciesString)
```

I guess that's pretty much it.
